#!/bin/bash

ufw disable
yes | ufw reset
ufw allow 53 # dns tcp/udp
ufw allow 67/udp # dhcp
ufw allow ssh # ssh, remember to use ssh keys
ufw allow 80/tcp # http
ufw allow 443/tcp # https
ufw allow 51820/udp # wireguard
ufw enable

