version: "3"

services:
  unbound:
    container_name: unbound
    # https://hub.docker.com/r/klutchell/unbound
    image: klutchell/unbound
    ports:
      - "5353:5053/tcp"
      - "5353:5053/udp"
    restart: unless-stopped
