version: '3.7'

services:

  terraria:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - world=Lordran.wld
    working_dir: /terraria/tshock
    #working_dir: /terraria/vanilla
    volumes:
      - ./:/config
    ports:
      - 7777:7777
    tty: true
    command: mono --server --gc=sgen -O=all TerrariaServer.exe -config /config/serverconfig.txt
